services:
    laravel-docker:
        container_name: laravel-docker
        build: .
        ports:
          - 8080:80


    # MySQL 8.0 container
    mysql_db:
        image: mysql:latest
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: laravel_docker_test
        ports:
            - "3307:3306"

  # phpMyAdmin Container
    phpmyadmin:
        image: phpmyadmin:latest
        container_name: phpmyadmin
        ports:
            - "9001:80"
        environment:
            - PMA_HOST=mysql_db
            - PMA_USER=root
            - PMA_PASSWORD=root

